<?php

namespace AppBundle\Repository;

/**
 * SmsTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SMSInRepository extends \Doctrine\ORM\EntityRepository
{
}
